#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
ends_with_ts=".*\.ts$"
ends_with_scss=".*\.scss$"
all_ts_files=""
all_scss_files=""
linter_exit_code=1
all_files_to_commit=$(git diff --name-only --cached)
for file in $all_files_to_commit
do
  if echo "$file" | grep "$ends_with_ts"; then
    all_ts_files="${all_ts_files}${file} "
  fi
  if echo "$file" | grep "$ends_with_scss"; then
    all_scss_files="${all_scss_files}${file} "
  fi
done
./node_modules/.bin/eslint $all_ts_files --quiet --fix && ./node_modules/.bin/stylelint $all_scss_files --stdin --quiet --fix
linter_exit_code=$?
git add -f $all_ts_files $all_scss_files
if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Linter errors has occurred ( ⚈̥̥̥̥̥́⌢⚈̥̥̥̥̥̀ )${NC}"
  exit 1
else
  echo "${GREEN} ✔ Eslint and Stylelint did not find any errors ( ◕‿◕ )${NC}"
  exit 0
fi
