#!/bin/sh
all_files_to_commit=$(git diff --name-only --cached)
ends_with_ts=".*\.ts$"
ends_with_scss=".*\.scss$"
all_ts_files=""
all_scss_files=""
for file in $all_files_to_commit
do
  if echo "$file" | grep "$ends_with_ts"; then
    all_ts_files="${all_ts_files}${file} "
  fi
  if echo "$file" | grep "$ends_with_scss"; then
    all_scss_files="${all_scss_files}${file} "
  fi
done
./node_modules/.bin/eslint $all_ts_files --quiet --fix && ./node_modules/.bin/stylelint $all_scss_files --stdin --quiet --fix
if [ $? -ne 0 ]
then
  echo Linter errors has occured
  exit 1
else
  echo Eslint and Stylelint did not find any errors
  exit 0
fi
